name: Test Documentation

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'docs/**'

  push:
    branches:
      - dev
    paths:
      - 'docs/**'
      - '.github/workflows/docs-test.yml'
      
  workflow_dispatch: 

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme recommonmark sphinx_panels sphinx_copybutton

      - name: Build Sphinx site
        run: |
          cd docs
          make html
