name: Sync from Dev to Lab

on:
  push:
    branches:
      - dev
    paths:
      - 'gym_vectorvelocity/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Checkout Lab Branch
      run: |
        git fetch origin
        git checkout -b lab origin/lab || git checkout --orphan lab

    - name: Copy gym_vectorvelocity Directory
      run: |
        git checkout dev -- gym_vectorvelocity

    - name: Commit Changes
      run: |
        git add gym_vectorvelocity
        git commit -m "Sync gym_vectorvelocity from dev to lab"

    - name: Push to Lab Branch
      run: |
        git push --force --set-upstream origin lab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
